server:
  port: "80"
  base_url: "http://localhost:80"

database:
  host: "prod-db-host"
  port: "5432"
  user: "prod_user"
  password: "prod_pass"
  name: "prod_db"

utils:
  jwt_secret: "mySecret"
  jwt_token_duration: "24h"

email:
  host: "smtp.gmail.com"
  port: "587"
  user: "your-user@gmail.com"
  password: "your-password"